defmodule Juntos.Repo.Migrations.AddConferencesAndTicketTiers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticket_tiers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :price_cents, :bigint, null: false, default: 0
      add :quantity, :bigint
      add :sold_count, :bigint, null: false, default: 0
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conference_id, :uuid, null: false
    end

    create table(:conferences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:ticket_tiers) do
      modify :conference_id,
             references(:conferences,
               column: :id,
               name: "ticket_tiers_conference_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conferences) do
      add :name, :text, null: false
      add :slug, :citext, null: false
      add :description, :text
      add :location, :text
      add :status, :text, null: false, default: "draft"
      add :starts_at, :utc_datetime
      add :ends_at, :utc_datetime
      add :cfp_opens_at, :utc_datetime
      add :cfp_closes_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organizer_id,
          references(:users,
            column: :id,
            name: "conferences_organizer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:conferences, [:slug], name: "conferences_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:conferences, [:slug], name: "conferences_unique_slug_index")

    drop constraint(:conferences, "conferences_organizer_id_fkey")

    alter table(:conferences) do
      remove :organizer_id
      remove :updated_at
      remove :inserted_at
      remove :cfp_closes_at
      remove :cfp_opens_at
      remove :ends_at
      remove :starts_at
      remove :status
      remove :location
      remove :description
      remove :slug
      remove :name
    end

    drop constraint(:ticket_tiers, "ticket_tiers_conference_id_fkey")

    alter table(:ticket_tiers) do
      modify :conference_id, :uuid
    end

    drop table(:conferences)

    drop table(:ticket_tiers)
  end
end
