defmodule Juntos.Repo.Migrations.AddUserProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :display_name, :text
      add :bio, :text
      add :avatar_url, :text
    end

    create table(:conference_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :speaker_name, :text
      add :speaker_bio, :text
      add :starts_at, :utc_datetime
      add :ends_at, :utc_datetime
      add :day_number, :bigint, null: false, default: 1
      add :room, :text
      add :session_type, :text, null: false, default: "talk"
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conference_id,
          references(:conferences,
            column: :id,
            name: "conference_sessions_conference_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:conference_sessions, "conference_sessions_conference_id_fkey")

    drop table(:conference_sessions)

    alter table(:users) do
      remove :avatar_url
      remove :bio
      remove :display_name
    end
  end
end
