defmodule Juntos.Repo.Migrations.AddMessaging do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id, :uuid, null: false
      add :sender_id, :uuid, null: false
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :sender_id,
             references(:users,
               column: :id,
               name: "messages_sender_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :subject, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:conversation_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :last_read_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_participants_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "conversation_participants_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:conversation_participants, [:conversation_id, :user_id],
             name: "conversation_participants_unique_participant_index"
           )
  end

  def down do
    drop_if_exists unique_index(:conversation_participants, [:conversation_id, :user_id],
                     name: "conversation_participants_unique_participant_index"
                   )

    drop constraint(:conversation_participants, "conversation_participants_conversation_id_fkey")

    drop constraint(:conversation_participants, "conversation_participants_user_id_fkey")

    drop table(:conversation_participants)

    alter table(:conversations) do
      remove :updated_at
      remove :inserted_at
      remove :subject
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop constraint(:messages, "messages_sender_id_fkey")

    alter table(:messages) do
      modify :sender_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop table(:messages)
  end
end
